---
title: "flim_biofilm"
output: html_document
---
```{r packages}
require(dplyr)
require(ggplot2)
require(gridExtra)
require(grid)
require(extrafont)
require(ggforce)
require(scales)
library(RColorBrewer)
library(data.table)
library(fasano.franceschini.test)

```


```{r colors and shapes}

circleFun <- function(center = c(0.5,0),diameter = 1 , npoints = 100){
    r = diameter / 2
    tt <- seq(0,2*pi,length.out = npoints)
    xx <- center[1] + r * cos(tt)
    yy <- center[2] + r * sin(tt)
    return(data.frame(x = xx, y = yy))
}

circle1<- circleFun()


color_map_1<-c(
  "Enzyme-bound NADH"="#0072b2",
  "LDH NADH"= "#0072b2", 
  "Free NADH"= "#e69f00",
   "PVD"="#d55e00",
  "PYO"="#56b4e9", 
  "PYO (Reduced)" = "#56b4e9",
  "OHPhz (Reduced)" = "#009e73", 
  "FAD" = "#EE9B00" , 
   "CPX" = "#9B2226" ,
  "OLS" = "black" , 
  "PVD + Fe" = "#f0e442" )

color_map_2<-c(
  "Enzyme-bound NADH"="#272727",
  "LDH NADH"="#272727",
  "Free NADH"="#696773",
   "PVD"="#FED766",
  "PYO"="#009FB7")

#EFF1F3

shape_maps<-c(
  "LDH NADH"=22,
  "Free NADH"=23,
   "PVD"=24,
  "PYO (Reduced)" = 25 , 
  "OHPhz (Reduced)" = 21,
  "OLS" = 8)


# media color maps
media_colors <- c(
  "ASM" = "#444444", 
  "M9 suc" = "#D3B2D9" ,
  "M9 suc+sup" = "#FF7700" )

media_shapes <- c(
  "ASM" = 21 , 
  "M9 suc" = 22  ,
  "M9 suc+sup" = 23 )

color_shape_maps<-c(
  "Enzyme-bound NADH"= 0,
  "LDH NADH"= 0,
  "Free NADH"=5,
   "PVD"= 2 ,
  "PYO"= 6 )


toc_shape_maps<-c(
  "PYO (Reduced)"= 25,
  "0" = 19,
  "100" = 19,
  '200' = 19,
  "300" = 19,
  "400" = 19,
  "500" = 19,
  "600" = 19, 
  "700" = 19,
  "800" = 19,
  "900" = 19,
  "1000" = 19,
  "Rothia \n cross-feeding \n hypoxic" = 5,
  "Uninoc" = 15
  )

# gradient color map
yellow_blue_1 <- c('#EDF8B1',  '#C7E9B4' , "#41B6C4" , "#225EA8" , "#081D58" )
yellow_blue <- c('#EDF8B1',  '#C7E9B4' , "#41B6C4" , "#225EA8"  )
yellow_red <- c("#ffba08", "#f48c06",  "#dc2f02", "#9d0208") 
green_red_1 <- c("#90BE6D" , "#F9C74F", "#F8961E", "#F3722C" ,  "#F94144")
green_red <- c("#90BE6D" , "#F9C74F",  "#F94144")
blue_yellow_orange <- c("#3BCFD4", "#D7FC05", "#EC6E20")
purple_green <- c('#7C65A9' ,"#96D4CA") 
#
blue_green_orange <- c("#0088FF" , "#5BCA7A", "#FF6200" )

white_black <- c("#F8F8FF", "#CAC9CD" ,  "#9B9A9C" , "#6D6A6A" , "#3E3B39" , "#100C07" )


# depth
depth_colors <- c("#1295E4", "#36AFAF", "#5BCA7A", "#9CA049", "#BD8B30" , "#DE7618" , "#B7094C" , "#A01A58" , "#892B64", "#723C70", "#5C4D7D")

depth_lines <- c("solid", "dotted", "dashed", "longdash", "solid", "dotted", "dashed", "longdash",  "dotted", "dashed", "solid")

```


```{r paths and data}

# /Users/sltg/Desktop/Biofilm_June18_2020/WT_M9/WT_M9_3D_plate3/29p_300d1000.bmp 
# /Users/sltg/Desktop/Biofilm_June18_2020/phzko_M9/phzko_M9_3D_plate3/39p_800d1000.bmp



# reference means 
ref <- read.csv( file = "/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/Processed/ref_flim_means.csv")

# biofilm depth data
# g and s data
biofilm <- read.csv(file =  '/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/Processed/df_biofilm_flim.csv', header=T)

```



```{r lifetime phasor }

phasorFun <- function(omega,time){
  #convert megaheartz to nanoseconds
  NS =omega*2*pi/1000
  g=1/(1+(NS*time)^2)
  s=NS*time/(1+(NS*time)^2)
 return(data.frame(mean_g1=g, mean_s1=s, lifetime=time))
}


enzymeNADH<-phasorFun(80,3.2)
phasorFun(80,10)
enzymeNADH$object<-c("LDH NADH")

oxlipid<-phasorFun(80,7.8)

oxlipid$object<-c("OLS")

ref <- rbind(ref, enzymeNADH)
ref <- rbind(ref, oxlipid)


```


```{r format biofilm flim data}

# get depth from filename
biofilm$depth <- gsub(pattern = ".*[0-9]p_", replacement="", x= biofilm$FileName )
biofilm$depth <- gsub(pattern = "CG0T.*" , replacement = "", x=biofilm$depth)
biofilm$depth <- gsub(pattern = "d.*" , replacement = "", x=biofilm$depth)

subset(biofilm, condition == "WT_M9suc" & plate == "plate1" & depth == "200")

# get strain (wt vs phz ko)
biofilm$strain <- ifelse( grepl(x=biofilm$condition, pattern="WT"), "WT", "Δphz") 

# get media (asm or m9 succinate)
biofilm$media <- ifelse( grepl(x=biofilm$condition, pattern="ASM"), "ASM", "M9 suc") 



biofilm <- subset(biofilm, FileName!="/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/FLIM/biofilm/phzko_ASM/plate1/45p_75d000$CG0T_0-1__ch1_h1_h2.R64")

```

```{r blank media}

blank_media <- read.csv('/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/Processed/df_blank_media_flim.csv')
blank_media$plate <- 'plate1'
blank_media$strain <-'WT'
blank_media$depth <- 'Uninoc'
blank_media$media <- blank_media$condition


copy <- blank_media
copy$strain <- 'Δphz'

blank_media <- rbind(blank_media, copy)

blank_media$media <- ifelse(  grepl(blank_media$condition, pattern = "ASM"), "ASM", "M9 suc"  )

```


```{r plot phasor}

# order biofilm depth 
#biofilm$depth <- factor(as.character(biofilm$depth))

biofilm$depth <- factor(biofilm$depth , levels = c("0","100","200","300", "400","500","600","700","800","900","1000", "Uninoc")) 

biofilm <- subset(biofilm, depth!= 75 )

biofilm_phasor <- ggplot() + 
  geom_path(data=subset(circle1, y>0),aes(x=x,y=y))+
  geom_bin2d(data = biofilm, aes(x=g1, y=s1 ), bins=150)+
  facet_grid(.~strain + media )+
  scale_fill_gradientn( colors = rev(yellow_blue), "Number \n of pixels",
                        labels = label_scientific())+
   theme( plot.background = element_rect(fill="white", color="white"),
        panel.background = element_rect(fill="white", color="black"),
        panel.grid = element_blank(), 
        axis.text=element_text(color="black",size=12),
        axis.ticks=element_blank(),
        axis.title.y = element_text(color="black", size=12),
      axis.title.x= element_text(color="black", size=12),
        strip.background = element_rect(color="black", fill="white"),
        strip.text =element_text(color="black", size=12),
                               legend.text=element_text(size=10),
     strip.text.y=element_text(angle=0),
     strip.text.x=element_text(angle=0),
   plot.title = element_text(hjust = 0.5, size=12),
        legend.title=element_text(size=10) ,
   legend.background = element_rect(color='white' , fill='white'),
   legend.key = element_rect(color='white', fill='white'),
   legend.position = 'none' ) +
    xlab(expression('G=M'%*%'cos('~phi~')'))+
  ylab(expression('S=M'%*%'sin('~phi~')'))+
    geom_path(data=subset(circle1, y>0),aes(x=x,y=y))+
  scale_x_continuous(breaks=pretty_breaks(n=1))+
  scale_y_continuous(breaks=pretty_breaks(n=1), limits = c(0,1))+
  geom_point( data = ref, aes(x=mean_g1, y=mean_s1, shape=object), fill="black", size=2)+
  scale_shape_manual( values = shape_maps )


biofilm_phasor_gradientonly <- 
   ggplot() + 
  geom_path(data=subset(circle1, y>0),aes(x=x,y=y))+
  geom_bin2d(data = biofilm, aes(x=g1, y=s1 ), bins=150)+
  scale_fill_gradientn( colors = rev(yellow_blue), "Number \n of pixels",
                        labels = label_scientific( digits=1),  breaks=c(10000, 50000) ) +
   theme( plot.background = element_rect(fill="white", color="white"),
        panel.background = element_rect(fill="white", color="black"),
        panel.grid = element_blank(), 
        axis.text=element_text(color="black",size=12),
        axis.ticks=element_blank(),
        axis.title.y = element_text(color="black", size=12),
      axis.title.x= element_text(color="black", size=12),
        strip.background = element_rect(color="black", fill="white"),
        strip.text =element_text(color="black", size=12),
                               legend.text=element_text(size=12),
     strip.text.y=element_text(angle=0),
     strip.text.x=element_text(angle=0),
   plot.title = element_text(hjust = 0.5, size=12),
   plot.margin =margin(l=10), 
        legend.title=element_text(size=12) ,
   legend.background = element_rect(color='white' , fill='white'),
   legend.key = element_rect(color='white', fill='white'),
   legend.position = 'bottom' ) +
    xlab(expression('G=M'%*%'cos('~phi~')'))+
  ylab(expression('S=M'%*%'sin('~phi~')'))+
    geom_path(data=subset(circle1, y>0),aes(x=x,y=y))+
  scale_x_continuous(breaks=pretty_breaks(n=2))+
  scale_y_continuous(breaks=pretty_breaks(n=2), limits = c(0,1))
  

biofilm_gradient_legend <- cowplot::get_legend(biofilm_phasor_gradientonly)

biofilm_phasor_shapesonly <- 
   ggplot() + 
    geom_point( data = ref, aes(x=mean_g1, y=mean_s1, shape=object), size=1,
                             stroke=1, fill="black")+
   theme( plot.background = element_rect(fill="white", color="white"),
        panel.background = element_rect(fill="white", color="black"),
        panel.grid = element_blank(), 
        axis.text=element_text(color="black",size=12),
        axis.ticks=element_blank(),
        axis.title.y = element_text(color="black", size=12),
      axis.title.x= element_text(color="black", size=12),
        strip.background = element_rect(color="black", fill="white"),
        strip.text =element_text(color="black", size=12),
                               legend.text=element_text(size=12),
     strip.text.y=element_text(angle=0),
     strip.text.x=element_text(angle=0),
   plot.title = element_text(hjust = 0.5, size=12),
   plot.margin =margin(l=10), 
        legend.title=element_text(size=12) ,
   legend.background = element_rect(color='white' , fill='white'),
   legend.key = element_rect(color='white', fill='white'),
   legend.position = 'bottom' ) +
    xlab(expression('G=M'%*%'cos('~phi~')'))+
  ylab(expression('S=M'%*%'sin('~phi~')'))+
    geom_path(data=subset(circle1, y>0),aes(x=x,y=y))+
  scale_x_continuous(breaks=pretty_breaks(n=3))+
  scale_y_continuous(breaks=pretty_breaks(n=3), limits = c(0,1))+
  scale_shape_manual( values = shape_maps, "Pure solutions" )

biofilm_shapes_legend <- cowplot::get_legend(biofilm_phasor_shapesonly)
  
biofilm_melt <- reshape2::melt(biofilm, id = c("X", "FileName", "x", "y", "dc", "condition", "plate", "depth", "strain", "media"))

# only keep s1, g1
biofilm_melt <- subset(biofilm_melt, variable == "s1" | variable == "g1")

biofilm_melt$variable <- ifelse( biofilm_melt$variable == "s1", "S", "G"  )

# only keep within axis ranges
biofilm_melt <- subset(biofilm_melt, c((variable=="S" & value < 0.55) | (variable == "G" & value <1.1)) )
media_melt <- reshape2::melt(blank_media, id = c("X", "FileName", "x", "y", "dc", "condition", "plate", "depth", "strain", "media"))
media_melt <- subset(media_melt, variable == "s1" | variable == "g1")
media_melt$variable <- ifelse( media_melt$variable == "s1", "S", "G"  )


biofilm_melt <- rbind(biofilm_melt, media_melt)

both_density <- ggplot() + 
   geom_density(data = biofilm_melt, aes(x = value, color = depth, linetype = depth), size=.8) + 
  facet_grid(strain+media~variable , switch="y", space="free_x", scale="free") +
  scale_color_manual( values = c( depth_colors, "#555555" ),"Depth (µm)"  )+
  theme( plot.background = element_rect(fill="white", color="white"),
        panel.background = element_rect(fill="white", color="black"),
        panel.grid = element_blank(), 
        axis.text.x=element_text(size=12),
        axis.text.y = element_blank(),
        axis.ticks=element_blank(),
        axis.title.y = element_text(color="black", size=12),
        axis.title.x=element_blank(),
        strip.background = element_rect(color="black", fill="white"),
        strip.text =element_text(color="black", size=12),
                               legend.text=element_text(size=12),
     strip.text.y=element_text(angle=0),
     strip.text.x=element_text(angle=0),
   plot.title = element_text(hjust = 0.5, size=12),
        legend.title= element_text(size=12, color='black'),
   legend.key =  element_rect(fill='white', color='white'))+
   # xlab(expression('G=M'%*%'cos('~phi~')'))+
  ylab("Density")+
  scale_x_continuous( breaks=pretty_breaks(n=3))+
  scale_linetype_manual(values = c( depth_lines, "dotted" ), "Depth (µm)")


# g1_density <- ggplot() + geom_density(data = biofilm, aes(x = g1, color = depth, linetype = depth )) + 
#   facet_grid(strain+media~. , switch="both") +
#   scale_color_manual( values = depth_colors,"Depth (µm)"  )+
#   theme( plot.background = element_rect(fill="white", color="white"),
#         panel.background = element_rect(fill="white", color="black"),
#         panel.grid = element_blank(), 
#         axis.text.x=element_text(color="black",size=12),
#         axis.text.y = element_blank(),
#         axis.ticks=element_blank(),
#         axis.title = element_text(color="black", size=12),
#         strip.background = element_rect(color="black", fill="white"),
#         strip.text =element_text(color="black", size=12),
#                                legend.text=element_text(size=12),
#      strip.text.y=element_text(angle=0),
#      strip.text.x=element_text(angle=0),
#    plot.title = element_text(hjust = 0.5, size=12),
#         legend.title= element_text(size=12, color='black'),
#    legend.position='none',
#    legend.key =  element_rect(fill='white', color='white'))+
#     xlab(expression('G=M'%*%'cos('~phi~')'))+
#   ylab("Density")+
#   scale_x_continuous( breaks=pretty_breaks(n=3), limits = c(0,1))+
#   scale_linetype_manual(values = depth_lines, "Depth (µm)")
# 
# 
# s1_density <- ggplot() + geom_density(data = biofilm, aes(x = s1, color = depth, linetype = depth )) + 
#   facet_grid(strain+media~. ) +
#   scale_color_manual( values = depth_colors,"Depth (µm)"  )+
#   theme( plot.background = element_rect(fill="white", color="white"),
#         panel.background = element_rect(fill="white", color="black"),
#         panel.grid = element_blank(), 
#         axis.text.x =element_text(color="black",size=12),
#         axis.ticks=element_blank(),
#         axis.text.y= element_blank(),
#         axis.title = element_text(color="black", size=12),
#         strip.background = element_rect(color="black", fill="white"),
#         strip.text =element_blank(),
#                                legend.text=element_text(size=12),
#    plot.title = element_text(hjust = 0.5, size=12),
#         legend.title= element_text(size=12, color='black'), 
#    legend.key =  element_rect(fill='white', color='white'))+
#     xlab(expression('S=M'%*%'sin('~phi~')'))+
#   ylab("Density")+
#   scale_x_continuous( breaks=pretty_breaks(n=3), limits = c(0,0.55))+
#   scale_linetype_manual(values = depth_lines, "Depth (µm)")


```


```{r mean g and s}

mean_g_s <- biofilm %>% group_by(condition, plate, depth, FileName, strain, media) %>%
 summarise( G = mean(g1),S = mean(s1))

blank_g_s <- blank_media %>% group_by(condition, plate, depth, FileName, strain, media) %>%
 summarise( G = mean(g1),S = mean(s1))


mean_g_s <- rbind(mean_g_s, blank_g_s)

mean_g_s$depth <- factor(mean_g_s$depth, levels = c( "0", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000", 'Uninoc'))


biofilm_phasor_mean <- ggplot() + 
  geom_path(data=subset(circle1, y>0),aes(x=x,y=y))+
  facet_grid(.~strain + media )+
  scale_color_manual( values = c( depth_colors, "#6d6d6d" ))+
   theme( plot.background = element_rect(fill="white", color="white"),
        panel.background = element_rect(fill="white", color="black"),
        panel.grid = element_blank(), 
        axis.text=element_text(color="black",size=12),
        axis.ticks=element_blank(),
        axis.title.y = element_text(color="black", size=12),
      axis.title.x= element_text(color="black", size=12),
        strip.background = element_rect(color="black", fill="white"),
        strip.text =element_text(color="black", size=12),
                               legend.text=element_text(size=10),
     strip.text.y=element_text(angle=0),
     strip.text.x=element_text(angle=0),
   plot.title = element_text(hjust = 0.5, size=12),
        legend.title=element_text(size=10) ,
   legend.background = element_rect(color='white' , fill='white'),
   legend.key = element_rect(color='white', fill='white'),
   legend.position = 'none' ) +
    xlab(expression('G=M'%*%'cos('~phi~')'))+
  ylab(expression('S=M'%*%'sin('~phi~')'))+
    geom_path(data=subset(circle1, y>0),aes(x=x,y=y))+
  scale_x_continuous(breaks=pretty_breaks(n=1))+
  scale_y_continuous(breaks=pretty_breaks(n=1), limits = c(0,1))+
  geom_point( data = ref, aes(x=mean_g1, y=mean_s1, shape=object), fill="black", size=2)+
    geom_point(data = mean_g_s, aes(x=G, y=S, color = depth), size = 3, shape = c( rep(19, 132), rep(3, 8) ) )+
  scale_shape_manual( values = shape_maps )



biofilm_phasor_mean_shapes_colors <- ggplot() + 
  geom_path(data=subset(circle1, y>0),aes(x=x,y=y))+
  geom_point(data = mean_g_s, aes(x=G, y=S, color = depth, shape = depth), size = 2 ) +
  facet_grid(.~strain + media )+
  scale_color_manual( values = c( depth_colors, "#6d6d6d" ), "Depth (µm)")+
  scale_shape_manual( values = c( rep(19, 11), 3) , "Depth (µm)") + 
   theme( plot.background = element_rect(fill="white", color="white"),
        panel.background = element_rect(fill="white", color="black"),
        panel.grid = element_blank(), 
        axis.text=element_text(color="black",size=12),
        axis.ticks=element_blank(),
        axis.title.y = element_text(color="black", size=12),
      axis.title.x= element_text(color="black", size=12),
        strip.background = element_rect(color="black", fill="white"),
        strip.text =element_text(color="black", size=12),
                               legend.text=element_text(size=10),
     strip.text.y=element_text(angle=0),
     strip.text.x=element_text(angle=0),
   plot.title = element_text(hjust = 0.5, size=12),
    plot.margin =margin(l=10),
        legend.title=element_text(size=10) ,
   legend.background = element_rect(color='white' , fill='white'),
   legend.key = element_rect(color='white', fill='white'),
   legend.position = "bottom") +
    xlab(expression('G=M'%*%'cos('~phi~')'))+
  ylab(expression('S=M'%*%'sin('~phi~')'))+
    geom_path(data=subset(circle1, y>0),aes(x=x,y=y))+
  scale_x_continuous(breaks=pretty_breaks(n=1))+
  scale_y_continuous(breaks=pretty_breaks(n=1), limits = c(0,1))




biofilm_mean_legend <- cowplot::get_legend(biofilm_phasor_mean_shapes_colors)
  

```

```{r figure 3 grids}

tablea<-textGrob(c("A"), gp=gpar(fontsize=40), vjust=c(-1,0), hjust=c(.5,0))
tableb<-textGrob(c("B"), gp=gpar(fontsize=40), vjust=c(-1,0), hjust=c(.5,0))
tablec<-textGrob(c("C"), gp=gpar(fontsize=40), vjust=c(-1,0), hjust=c(.5,0))

# panel_a_legends <- arrangeGrob(biofilm_shapes_legend, biofilm_gradient_legend, nrow=2 )
#panel_a<- arrangeGrob( arrangeGrob(tablea, biofilm_phasor, ncol=2, widths=c(1,12)), panel_a_legends, nrow=2, heights=c(3,2),padding = c(.2) )
panel_a<- arrangeGrob( 
  arrangeGrob(tablea, biofilm_phasor, ncol=2, widths = c(1,12)),
              biofilm_gradient_legend, nrow =2, heights = c(3,1), padding = c(.2))


panel_b <- arrangeGrob(tableb, both_density , ncol=2, widths=c(1,12))
# panel_b <- arrangeGrob(tableb, g1_density , ncol=2, widths=c(1,12))
# panel_c <- arrangeGrob(tablec, s1_density , ncol=2, widths=c(1,12))
# panel_bc <- arrangeGrob(panel_b,panel_c, ncol=2, widths=c(1,1.2))

panel_c<- arrangeGrob( 
  arrangeGrob(tablec, biofilm_phasor_mean, ncol=2, widths = c(1,12)),
              biofilm_mean_legend, nrow =2, heights = c(3,1), padding = c(.2))


figure3 <- arrangeGrob(panel_a, panel_b, panel_c,biofilm_shapes_legend, nrow=4, heights=c(.9,1,.9,.2))

# ggsave(plot=figure3,filename ="/Users/sltg/Documents/GitHub/PseudomonasFLIM/Output/Paper/Figures/fig3_biofilm_phasor.svg", device = 'svg', height=10, width= 7)

# ggsave(plot=figure3,filename ="/Users/sltg/Documents/GitHub/PseudomonasFLIM/Output/Paper/Figures/fig3_biofilm_phasor.tiff", device = 'tiff', height=10, width= 7)


# ggsave(plot=biofilm_shapes_legend,filename ="/Users/sltg/Documents/GitHub/PseudomonasFLIM/Output/Paper/Figures/legend_biofilm_phasor.svg", device ='svg', height=2, width=6.2 )


```


```{r example images}

# ASM phz ko = plate 2

# ASM WT = plate 1 
# 20p_0d000$CG0T_0-1__ch1_h1_h2.R64
# 49p_500d501$CG0T_0-1__ch1_h1_h2.R64
# 59p_1000d001$CG0T_0-1__ch1_h1_h2.R64

# M9 succinate ko = plate 1 
# 10p_0d000$CG0T_0-1__ch1_h1_h2.R64
# 34p_500d501$CG0T_0-1__ch1_h1_h2.R64
# 40p_1000d001$CG0T_0-1__ch1_h1_h2.R64

# WT M9 succinate 
# 11p_0d000$CG0T_0-1__ch1_h1_h2.R64
# 34p_500d501$CG0T_0-1__ch1_h1_h2.R64
# 39p_1000d001$CG0T_0-1__ch1_h1_h2.R64

# example images

# /Users/sltg/Desktop/Biofilm_June18_2020/WT_M9/WT_M9_3D_plate3/29p_300d1000.bmp 
# /Users/sltg/Desktop/Biofilm_June18_2020/phzko_M9/phzko_M9_3D_plate3/39p_800d1000.bmp


ex_file_paths <- c(
  "/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/FLIM/biofilm/phzko_M9suc/plate1/10p_0d000$CG0T_0-1__ch1_h1_h2.R64", 
  "/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/FLIM/biofilm/WT_ASM/plate1/20p_0d000$CG0T_0-1__ch1_h1_h2.R64",
  "/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/FLIM/biofilm/WT_M9suc/plate1/11p_0d000$CG0T_0-1__ch1_h1_h2.R64",
  "/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/FLIM/biofilm/phzko_ASM/plate1/15p_0d000$CG0T_0-1__ch1_h1_h2.R64", 
  "/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/FLIM/biofilm/phzko_M9suc/plate3/39p_800d801$CG0T_0-1__ch1_h1_h2.R64",
  "/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/FLIM/biofilm/WT_M9suc/plate2/35p_700d701$CG0T_0-1__ch1_h1_h2.R64",
  "/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/FLIM/biofilm/WT_ASM/plate1/59p_1000d001$CG0T_0-1__ch1_h1_h2.R64",
  "/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/FLIM/biofilm/phzko_ASM/plate3/54p_400d401$CG0T_0-1__ch1_h1_h2.R64"
)


biofilm_ex <- biofilm [ biofilm$FileName %in% ex_file_paths, ]




### top vs bottom
biofilm_ex$depth_ex <- ifelse(biofilm_ex$depth == "0", 'surface', 'bottom')


```


```{r example images intensity plot }

# normalize intensity 
biofilm_ex <- biofilm_ex %>% group_by(FileName) %>%
  mutate( max_dc = max(dc), avg_dc = mean(dc))

biofilm_ex$norm_dc <- biofilm_ex$dc / biofilm_ex$max_dc

biofilm_ex$depth_ex <- factor(biofilm_ex$depth_ex, levels = c('surface', 'bottom'))
rainbow = brewer.pal(name = 'Spectral', 10)



biofilm_ex_dc <- ggplot() + geom_tile(data=subset( biofilm_ex ), aes(x=x,y=y, fill=(( 
  norm_dc))))+
facet_grid(depth_ex ~ strain + media ) + 
scale_fill_gradientn( colours = rev(white_black) ,"Normalized \n Fluorescent \n intensity")+
   theme( plot.background = element_rect(fill="white", color="white"),
        panel.background = element_rect(fill="white", color="white"),
                plot.margin = margin(0,0,0,0 , "cm"), 
        panel.grid = element_blank(), 
        axis.text=element_text(color = "white", size=12),
        axis.ticks=element_blank(),
        axis.title = element_text(color="white", size=12),
        strip.background = element_rect(color="black", fill="white"),
        strip.text =element_text(color="black", size=12),
     strip.text.y=element_text(angle=0),
     strip.text.x=element_text(angle=0),
   plot.title = element_text(hjust = 0.5, size=12),
        legend.title=element_text(size=12, color="black") , 
   legend.text=element_text(color="black", size=12),
   legend.margin=margin(-1,0,0,0, "cm"),
   legend.position = 'bottom')
   
```


```{r flim phasor color mapping } 

### bin data 
get_binned_data <- function(df) {
   ex_plot <- ggplot() + geom_bin2d(data = df , aes(x=g1,y=s1, color=dc), bins=250)+
  geom_path(data=subset(circle1, y>0),aes(x=x,y=y)) 
  
  # extract binned data
ex_binned_data <- ggplot_build( ex_plot )$data[[1]]

colnames(ex_binned_data)[c(5,6)] <- c('binned_g1' , 'binned_s1')

ex_binned_data <- ex_binned_data[order(ex_binned_data$binned_g1+1 * ex_binned_data$binned_s1+1 ),]

  }

ex_binned_data <- biofilm_ex %>% group_by(FileName, strain, media) %>%
  group_modify( ~ get_binned_data(.x) )


### assign colors to bins
ex_binned_data <- data.frame(ex_binned_data)

ex_binned_data <- ex_binned_data[order( (ex_binned_data$binned_g1 * ex_binned_data$binned_s1 )),]

# color for each bin
coul <- colorRampPalette( colors =  c(blue_green_orange))(nrow(ex_binned_data))

ex_binned_data <- cbind( ex_binned_data , coul)


### map colors back to bins
ex_mapped <- data.frame()

for (file in levels(factor(ex_binned_data$FileName)) ) {
  print(file)
  biofilm_sub <- subset(biofilm_ex, FileName == file )
  binned_sub <- subset(ex_binned_data, FileName == file)
  
  setDT(biofilm_sub)
  setDT(binned_sub)
  
# map binned data colors back onto all ~63,000 pixels
  mapped_sub <- biofilm_sub[binned_sub, on = .(g1 >= xmin , g1 <= xmax,             
                           s1 >= ymin , s1 <= ymax), nomatch = NA, 
             .(g1, s1, dc, xmin, xmax, ymin, ymax, coul, x,y, FileName,  strain, media, depth, depth_ex, binned_g1,binned_s1)] 
  
  # append
  ex_mapped <- rbind(ex_mapped, mapped_sub)
  }


ex_mapped$depth_ex <- factor(ex_mapped$depth_ex, levels = c('surface' , 'bottom'))

```

```{r example images flim color map}

# subset bottom and surface data
#surface <- subset(ex_mapped, depth_ex == "surface")
# bottom <- subset(ex_mapped, depth_ex == "bottom")

# color mapped lifetime 
 ex_color_mapped<- ggplot() + geom_tile(data=ex_mapped, aes(x=x,y=y), fill= ex_mapped$coul)+
  facet_grid(depth_ex ~ strain + media ) + 
   theme( plot.background = element_rect(fill="white", color="white"),
        panel.background = element_rect(fill="white", color="white"),
                              plot.margin = margin(0,0,-0.3,0 , "cm"), 
        panel.grid = element_blank(), 
        axis.text=element_text(color="white", size=12),
        axis.ticks=element_blank(),
        axis.title = element_text(color="white",size=12),
        strip.background = element_rect(color="black", fill="white"),
        strip.text =element_text(color="black", size=12),
                               legend.text=element_text(size=12),
     strip.text.y=element_text(angle=0),
     strip.text.x=element_text(angle=0),
   plot.title = element_text(hjust = 0.5, size=12),
        legend.title=element_text(size=12)) 
 
 
```


```{r phasor}

ex_mapped_phasor <- ggplot() + geom_point(data=ex_mapped, aes(x=g1,y=s1), color = ex_mapped$coul, size=0.1)+
   geom_path(data=subset(circle1, y>0),aes(x=x,y=y))+
    facet_grid(depth_ex ~ strain + media )  + 
        scale_x_continuous(breaks=pretty_breaks(n=1))+
  scale_y_continuous(breaks=pretty_breaks(n=1), limits = c(0,1)) +
      xlab(expression('G=M'%*%'cos('~phi~')'))+
  ylab(expression('S=M'%*%'sin('~phi~')')) + 
  geom_point( data = ref, aes(x=mean_g1, y=mean_s1, shape=object), fill="black", size=1)+ 
 theme( plot.background = element_rect(fill="white", color="white"),
                plot.margin = margin(-0.3,0,0,0 , "cm"), 
        panel.background = element_rect(fill="white", color="black"),
        panel.grid = element_blank(), 
        axis.text=element_text(color="black", size=12),
        axis.ticks=element_blank(),
        axis.title = element_text(color="black", size=12), 
        strip.background = element_rect(color="black", fill="white"),
                               legend.text=element_text(size=12),
        strip.text.x = element_text(color='black', size=12, angle = 0), 
 strip.text.y = element_text(color='black', size=12, angle = 0), 

        legend.position = 'none', 
   plot.title = element_text(hjust = 0.5, size=12),
        legend.title=element_text(size=16))+
      xlab(expression('G=M'%*%'cos('~phi~')'))+
  ylab(expression('S=M'%*%'sin('~phi~')'))+
  scale_shape_manual(values = shape_maps)


```

```{r fig4 panels}



tablea<-textGrob(c("A"), gp=gpar(fontsize=40), vjust=c(-1,0), hjust=c(.5,0))
tableb<-textGrob(c("B"), gp=gpar(fontsize=40), vjust=c(-1,0), hjust=c(.5,0))
tablec<-textGrob(c("C"), gp=gpar(fontsize=40), vjust=c(-1,0), hjust=c(.5,0))

panel_a <- arrangeGrob(tablea, biofilm_ex_dc, ncol=2, widths=c(1,12))
panel_b <- arrangeGrob(tableb, ex_color_mapped, ncol=2, widths=c(1,12))
panel_c <- arrangeGrob(tablec, ex_mapped_phasor, ncol=2, widths=c(1,12))

fig4 <- arrangeGrob(panel_a, panel_b, panel_c, heights=c(1.13,1))



#ggsave(plot=fig4,filename ="/Users/sltg/Documents/GitHub/PseudomonasFLIM/Output/Paper/Figures/fig4.jpeg", device ='jpeg', height= 8.64, width= 5.8)

# note fov is 114 um

ggsave(plot=biofilm_shapes_legend,filename ="/Users/sltg/Documents/GitHub/PseudomonasFLIM/Output/Paper/Figures/fig4_legend.svg", device ='svg', height=2 , width=5.8 )



ggsave(plot=fig4,filename ="/Users/sltg/Documents/GitHub/PseudomonasFLIM/Output/Paper/Figures/fig4.svg", device ='svg', height=8.9 , width=5.8 )

ggsave(plot=fig4,filename ="/Users/sltg/Documents/GitHub/PseudomonasFLIM/Output/Paper/Figures/fig4.eps", device ='eps', height=8.9 , width=5.8 )


ggsave(plot=fig4,filename ="/Users/sltg/Documents/GitHub/PseudomonasFLIM/Output/Paper/Figures/fig4.tiff", device ='tiff', height=8.9 , width=5.8 )

```

```{r distribution tests}

# test if the distributions of surface WT are different than phz ko 

# WT surface is shifted to left of phz ko


# ASM
wilcox.test( y = unlist(subset(biofilm, media == 'ASM' & depth ==0 & condition == 'phzko_ASM')[,c('g1')]),
             x = unlist(subset(biofilm, media == 'ASM' & depth == 0 & strain == "WT")[,c('g1')]),
             alternative = c('less'))

wilcox.test( y = unlist(subset(biofilm, media == 'ASM' & depth ==0 & condition == 'phzko_ASM')[,c('s1')]),
             x = unlist(subset(biofilm, media == 'ASM' & depth == 0 & strain == "WT")[,c('s1')]),
             alternative = c('less'))


# M9 succinate

wilcox.test( y = unlist(subset(biofilm, media == 'M9 suc' & depth ==0 & condition == 'phzko_M9suc')[,c('g1')]),
             x = unlist(subset(biofilm, media == 'M9 suc' & depth == 0 & strain == "WT")[,c('g1')]),
             alternative = c('less'))


wilcox.test( y = unlist(subset(biofilm, media == 'M9 suc' & depth ==0 & condition == 'phzko_M9suc')[,c('s1')]),
             x = unlist(subset(biofilm, media == 'M9 suc' & depth == 0 & strain == "WT")[,c('s1')]),
             alternative = c('less'))


```


```{r t test comparisons for mean G and S values}

depth_list <- c("100", "200", "300", "400", "500", "600", "700", "800", "900", "1000")


con_list1 <- c("WT_ASM", "WT_M9suc")
stat_df <- data.frame()
for (x in con_list1) {
  con_df <- subset(mean_g_s, condition == x)
    depth0 <- subset(con_df, depth == 0)
    for (d in depth_list) {
      d_test <- subset(con_df, depth == d)
      results <- t.test(depth0$G, d_test$G)
      temp <- data.frame( t(c( results$p.value, results$estimate, x, d, "G")))
      stat_df <- rbind(temp, stat_df)
      
      results <- t.test(depth0$S, d_test$S)
      temp <- data.frame( t(c( results$p.value, results$estimate, x, d, "S")))
      stat_df <- rbind(temp, stat_df)
    }
  
} 
stat_df$adj_p <- p.adjust(stat_df$V1 , method = "BH" )

#colnames(stat_df) <- c("p-value" , "mean_x", "mean_y", "media", "depth", "variable", "fdr")

stat_df2 <- data.frame()
con_list2 <- c("phzko_ASM", "phzko_M9suc")
for (x in con_list2) {
  con_df <- subset(mean_g_s, condition == x)
    depth0 <- subset(con_df, depth == 0)
    for (d in depth_list) {
      d_test <- subset(con_df, depth == d)
      results <- t.test(depth0$G, d_test$G)
      temp <- data.frame( t(c( results$p.value, results$estimate, x, d, "G")))
      stat_df2 <- rbind(temp, stat_df2)
      
      results <- t.test(depth0$S, d_test$S)
      temp <- data.frame( t(c( results$p.value, results$estimate, x, d, "S")))
      stat_df2 <- rbind(temp, stat_df2)
    }
  
} 
stat_df2$adj_p <- p.adjust(stat_df2$V1 , method = "BH" )

all_compare <- rbind(stat_df,stat_df2)

colnames(all_compare) <- c("p-value" , "mean_x", "mean_y", "media", "depth", "variable", "fdr")



write.csv(all_compare, '/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/Processed/stats_biofilm_depth_comparisons.csv')


```


```{r TOC}

asm_only <- subset(mean_g_s, strain == "WT" )
asm_only <- subset(asm_only, media == "ASM")

pyo_only <- subset(ref, object == "PYO (Reduced)")  

x_feed_means <- read.csv("/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/Processed/xfeed_means.csv")

x_feed_means <- subset(x_feed_means, media_sup == "M9 suc+sup")
colnames(x_feed_means) <- c("FileName", "depth", "S", "G")
x_feed_means$depth <- c("Rothia \n cross-feeding \n hypoxic")
x_feed_means$strain <- c("")
x_feed_means$media <- c("")
x_feed_means$plate <- c("")

asm_only <- rbind(asm_only, x_feed_means)



colnames(pyo_only) <- c("depth", "S", "G", "FileName")
pyo_only$strain <- c("")
pyo_only$media <- c("")
pyo_only$plate <- c("")

asm_only <- rbind(asm_only, pyo_only)

asm_only$depth <- factor(asm_only$depth, levels = c("0", "100", "200", "300", "400", "500", "600", "700", "800", "900","1000", "Rothia \n cross-feeding \n hypoxic", "PYO (Reduced)" , "Uninoc"))


toc_plot <- ggplot() + 
  geom_path(data=subset(circle1, y>0),aes(x=x,y=y))+
  scale_color_manual( values = c( depth_colors, "black" , "#6d6d6d", "black" ), "Biofilm \n Depth \n(µM)")+
   theme( plot.background = element_rect(fill="white", color="white"),
        panel.background = element_rect(fill="white", color="black"),
        panel.grid = element_blank(), 
        axis.text=element_text(color="black",size=12),
        axis.ticks=element_blank(),
        axis.title.y = element_text(color="black", size=12),
      axis.title.x= element_text(color="black", size=12),
        strip.background = element_rect(color="black", fill="white"),
        strip.text =element_text(color="black", size=12),
                               legend.text=element_text(size=10),
     strip.text.y=element_text(angle=0),
     strip.text.x=element_text(angle=0),
   plot.title = element_text(hjust = 0.5, size=12),
        legend.title=element_text(size=10) ,
   legend.background = element_rect(color='white' , fill='white'),
   legend.key = element_rect(color='white', fill='white'),
   legend.position = 'right' ) +
    xlab(expression('G=M'%*%'cos('~phi~')'))+
  ylab(expression('S=M'%*%'sin('~phi~')'))+
    geom_path(data=subset(circle1, y>0),aes(x=x,y=y))+
  scale_x_continuous(breaks=pretty_breaks(n=1))+
  scale_y_continuous(breaks=pretty_breaks(n=1), limits = c(0,1))+
#  geom_point( data =pyo_only, aes(x=mean_g1, y=mean_s1, shape = object, color = object), fill="black", size=4)+
    geom_point(data = asm_only, aes(x=G, y=S, color = depth, shape = depth), size = 4 )+
  scale_shape_manual( values = toc_shape_maps, "Biofilm \n Depth \n(µM)" )+
  xlim( -.001, 0.39)


ggsave(plot=toc_plot,filename ="/Users/sltg/Documents/GitHub/PseudomonasFLIM/Output/Paper/Figures/toc.svg", device ='svg', height= 5 , width=5 )


```