---
title: "spectral_phasor_purecomponents"
author: "tara"
date: "5/13/2020"
output: html_document
---


```{r packages}
require(dplyr)
require(ggplot2)
require(gridExtra)
require(grid)
require(extrafont)
require(ggforce)
require(scales)
library(RColorBrewer)

```



```{r colors and shapes}

circleFun <- function(center = c(0.5,0),diameter = 1 , npoints = 100){
    r = diameter / 2
    tt <- seq(0,2*pi,length.out = npoints)
    xx <- center[1] + r * cos(tt)
    yy <- center[2] + r * sin(tt)
    return(data.frame(x = xx, y = yy))
}

circle1<- circleFun()

color_map_1<-c(
  "Enzyme-bound NADH"="#0072b2",
  "MDH NADH"= "#0072b2", 
  "Free NADH"= "#e69f00",
   "PVD"="#d55e00",
  "PYO"="#56b4e9", 
  "PYO (Reduced)" = "#56b4e9",
  "OHPhz (Reduced)" = "#009e73", 
  "FAD" = "#EE9B00" , 
   "CPX" = "#9B2226" ,
  "OLS" = "black" , 
  "PVD + Fe" = "#f0e442" )

color_map_2<-c(
  "Enzyme-bound NADH"="#272727",
  "MDH NADH"="#272727",
  "Free NADH"="#696773",
   "PVD"="#FED766",
  "PYO"="#009FB7")

#EFF1F3

shape_maps<-c(
  "Enzyme-bound NADH"=22,
  "MDH NADH"=22,
  "Free NADH"=23,
   "PVD"=24,
  "PYO"=25 , 
  "PYO (Reduced)" = 25 , 
  "OHPhz (Reduced)" = 21,
  "FAD" = 21 , 
  "CPX" = 22 ,
  "OLS" = 8)



color_shape_maps<-c(
  "Enzyme-bound NADH"= 0,
  "MDH NADH"= 0,
  "Free NADH"=5,
   "PVD"= 2 ,
  "PYO"= 6 )

# gradient color map
yellow_blue_1 <- c('#EDF8B1',  '#C7E9B4' , "#41B6C4" , "#225EA8" , "#081D58" )
yellow_blue <- c('#EDF8B1',  '#C7E9B4' , "#41B6C4" , "#225EA8"  )
yellow_red <- c("#ffba08", "#f48c06",  "#dc2f02", "#9d0208") 
green_red_1 <- c("#90BE6D" , "#F9C74F", "#F8961E", "#F3722C" ,  "#F94144")
green_red <- c("#90BE6D" , "#F9C74F",  "#F94144")
```

```{r lifetime phasor }

phasorFun <- function(omega,time){
  #convert megaheartz to nanoseconds
  NS =omega*2*pi/1000
  g=1/(1+(NS*time)^2)
  s=NS*time/(1+(NS*time)^2)
 return(data.frame(mean_g1=g, mean_s1=s, lifetime=time))
}


enzymeNADH<-phasorFun(80,3.2)
phasorFun(80,10)
enzymeNADH$object<-c("Enzyme-bound NADH")

freeNADH<-phasorFun(80,.37)
freeNADH$object<-c("Free NADH")

oxlipid<-phasorFun(80,7.8)

oxlipid$object<-c("OLS")

```



```{r flim pixel data}


pixel_df <- read.csv(file =  '/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/Processed/df_refs_flim.csv', header=T)


#red_passive_pyo<-data.frame(0.0289,0.145,"")
#colnames(red_passive_pyo)<-colnames(enzymeNADH)[1:3]
#red_passive_pyo$object<-c("PYO")
#pyoverdine<-data.frame(0.162,0.367,  "")
#colnames(pyoverdine)<-colnames(enzymeNADH)[1:3]
#pyoverdine$object <- c("PVD")



#pixel_df$norm_dc = pixel_df$dc / max(pixel_df$dc)

# determine which pixels are singletons
pixel_df$info_concat <- paste(pixel_df$FileName, '_', round(pixel_df$g1, digits=6), '_' , round(pixel_df$s1, digits=6) ) 
pixel_df$singleton <- ifelse(duplicated(pixel_df$info_concat) , 'no', 'yes' ) 

# get object name 
pixel_df$object <- ifelse( grepl(pattern='NADH', x=pixel_df$FileName, ignore.case=TRUE), "Free NADH",
                           ifelse(grepl(pattern='pyoverdine_water', x=pixel_df$FileName, ignore.case=TRUE), "PVD" ,
                                  ifelse(grepl(pattern='ferritin', x=pixel_df$FileName, ignore.case=TRUE), "PVD + Fe" ,
                                      ifelse( grepl(pattern = 'PYO' , x=pixel_df$FileName, ignore.case=TRUE), "PYO (Reduced)",
                                              ifelse(  grepl(pattern = 'OHphz' , x=pixel_df$FileName, ignore.case=TRUE), "OHPhz (Reduced)" , NA)))))
                           
# get mean 
means <- subset(pixel_df, singleton=='no' ) %>%
    group_by(object) %>%
    dplyr::summarize(mean_s1 = mean(s1), mean_g1=mean(g1))


means$lifetime <- c('unknown')
flim_single_component<-rbind(enzymeNADH, means)
flim_single_component<-rbind(oxlipid, flim_single_component)


pixel_df$object <- ifelse(pixel_df$object == "Enzyme-bound NADH", "MDH NADH", pixel_df$object)
flim_single_component$object <- ifelse(flim_single_component$object == "Enzyme-bound NADH", "MDH NADH", flim_single_component$object)


pixel_df <- subset(pixel_df, object!="PVD + Fe")
flim_single_component <- subset(flim_single_component, object!="PVD + Fe")

flim_pure<-ggplot()+
  geom_bin2d(data=subset(pixel_df, singleton == 'no'), aes(x=g1, y=s1), bins=180)+
  geom_path(data=subset(circle1, y>0),aes(x=x,y=y))+
  geom_point(data = flim_single_component, aes(x=mean_g1, y=mean_s1, shape=object),color='black', size=4, 
             stroke=1,
             fill = c(color_map_1['OLS'],
                    color_map_1['MDH NADH'], 
                color_map_1['Free NADH'],
                      color_map_1['OHPhz (Reduced)'], 
                      color_map_1['PVD'], 
                      color_map_1['PYO']
                      ))+
  #scale_fill_manual( values = yellow_blue) +
  theme( plot.background = element_rect(fill="white", color="white"),
        panel.background = element_rect(fill="white", color="black"),
        panel.grid = element_blank(), 
        axis.text=element_text(color="black",size=16),
        axis.ticks=element_blank(),
        axis.title.y = element_text(color="black", size=16),
      axis.title.x= element_text(color="black", size=16),
        strip.background = element_rect(color="black", fill="white"),
        strip.text =element_text(color="black", size=12),
                               legend.text=element_text(size=12),
     strip.text.y=element_text(angle=0),
     strip.text.x=element_text(angle=0),
   plot.title = element_text(hjust = 0.5, size=12),
   legend.position = "none",
        legend.title=element_text(size=12) ) +
    xlab(expression('G=M'%*%'cos('~phi~')'))+
  ylab(expression('S=M'%*%'sin('~phi~')'))+
  scale_x_continuous(breaks=pretty_breaks(n=3))+
  scale_y_continuous(breaks=pretty_breaks(n=1), limits = c(0,1))+
   scale_fill_gradientn( colors = rev(yellow_blue), "Number \n of pixels")+
  scale_shape_manual(values = shape_maps)

gradient_only<-ggplot()+
  geom_bin2d(data=subset(pixel_df, singleton == 'no'), aes(x=g1, y=s1), bins=180)+
  geom_path(data=subset(circle1, y>0),aes(x=x,y=y))+
  #scale_fill_manual( values = yellow_blue) +
  theme( plot.background = element_rect(fill="white", color="white"),
        panel.background = element_rect(fill="white", color="black"),
        panel.grid = element_blank(), 
        axis.text=element_text(color="black",size=12),
        axis.ticks=element_blank(),
        axis.title.y = element_text(color="black", size=12),
      axis.title.x= element_text(color="black", size=12),
        strip.background = element_rect(color="black", fill="white"),
        strip.text =element_text(color="black", size=12),
                               legend.text=element_text(size=12),
     strip.text.y=element_text(angle=0),
     strip.text.x=element_text(angle=0),
   plot.title = element_text(hjust = 0.5, size=12),
   #legend.position = "none",
        legend.title=element_text(size=12) ) +
    xlab(expression('G=M'%*%'cos('~phi~')'))+
  ylab(expression('S=M'%*%'sin('~phi~')'))+
  scale_x_continuous(breaks=pretty_breaks(n=3))+
  scale_y_continuous(breaks=pretty_breaks(n=1), limits = c(0,1))+
   scale_fill_gradientn( colors = rev(yellow_blue), trans='log10', "Number \n of pixels")

shapes_only<-ggplot()+
  geom_path(data=subset(circle1, y>0),aes(x=x,y=y))+
  geom_point(data = flim_single_component, aes(x=mean_g1, y=mean_s1, shape=object, fill=object),color='black', size=4, 
             stroke=1)+
  #scale_fill_manual( values = yellow_blue) +
  theme( plot.background = element_rect(fill="white", color="white"),
        panel.background = element_rect(fill="white", color="black"),
        panel.grid = element_blank(), 
        axis.text=element_text(color="black",size=14),
        axis.ticks=element_blank(),
        axis.title.y = element_text(color="black", size=14),
      axis.title.x= element_text(color="black", size=14),
        strip.background = element_rect(color="black", fill="white"),
        strip.text =element_text(color="black", size=12),
                               legend.text=element_text(size=12),
     strip.text.y=element_text(angle=0),
     strip.text.x=element_text(angle=0),
   plot.title = element_text(hjust = 0.5, size=12),
   #legend.position = "none",
   legend.background = element_rect(fill='white'),
   legend.key = element_rect(fill='white'),
        legend.title=element_blank() ) +
    xlab(expression('G=M'%*%'cos('~phi~')'))+
  ylab(expression('S=M'%*%'sin('~phi~')'))+
  scale_x_continuous(breaks=pretty_breaks(n=3))+
  scale_y_continuous(breaks=pretty_breaks(n=1), limits = c(0,1))+
   scale_fill_manual(values = color_map_1)+
  scale_shape_manual(values = shape_maps)


flim_pure_shape_legend <- cowplot::get_legend(shapes_only)
flim_pure_gradient_legend <- cowplot::get_legend(gradient_only)



#ggsave(plot=flim_pure,filename ="/Volumes/GoogleDrive/My Drive/Spectral_lifetime_deconvolution/FIGURES/flim_phasor_pure.eps", device ='eps', height=3, width=5 )

```
 



```{r spectral data}
spectra <- read.csv( file= '/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/Processed/df_fig2_spectra.csv' ) 
semrock <- read.csv( file= '/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/Processed/df_fig2_semrock.csv' )

# dont use oh phz since non reproducible data
#spectra <- subset(spectra, Sample!= "Reduced OHPhz")

spectra$Sample <- ifelse( spectra$Sample ==  'Reduced PYO', 'PYO (Reduced)' , spectra$Sample )

ohphz <- read.csv( file = '/Users/sltg/Documents/GitHub/PseudomonasFLIM/Data/Processed/df_ohphz_spectra.csv' )
ggplot() + geom_line(data = ohphz, aes(x=Wavelength, y=Intensity, color=FileName))
ggplot() + geom_line(data = subset(ohphz, FileName!='hydrozyphenazine_reduced100uMslide_740nm20x5na473_697nm_10nmres_73p_25uspixd_13um_t1_l624.lsm') , aes(x=Wavelength, y=Intensity, color=FileName))

ggplot() + geom_line(data = subset(ohphz, FileName!='hydrozyphenazine_reduced100uMslide_740nm20x5na473_697nm_10nmres_62p_25uspixd_13um_t1_l624.lsm' & FileName!= 'hydrozyphenazine_reduced100uMslide_740nm20x5na473_697nm_10nmres_73p_25uspixd_13um_t1_l624.lsm' & FileName!= 'Old_OHPhz_TCEP_10p_25xW08NA_740nm_410_695_8_9nmsteps.lsm') , aes(x=Wavelength, y=Intensity, color=FileName))


ohphz_subset <- subset(ohphz, FileName == 'OHPhz_DTT_10p_25xW08NA_740nm_410_695_8_9nmsteps.lsm')
ohphz_subset$Sample <- ("OHPhz (Reduced)")

spectra <- rbind(spectra, ohphz_subset)

spectra_subset <- subset(spectra, Sample!='CPX' & Sample!='FAD' & Sample!='Reduced OHPhz')


spectra_plot <- ggplot() +
  geom_rect(mapping=aes(xmin=400, xmax=500, ymin=0, ymax=1), fill="#DCDCDC")  + 
    geom_line(data = spectra_subset, aes(x=Wavelength, y=Normalized, color=Sample ), size=1) +
  geom_point(data = spectra_subset, aes(x=Wavelength, y=Normalized, fill=Sample, shape= Sample), size=2) +
  scale_fill_manual( values = color_map_1) + 
  scale_shape_manual( values = shape_maps ) +
  scale_color_manual( values = color_map_1  ) + 
  theme( plot.background = element_rect(fill="white", color="white"),
        panel.background = element_rect(fill="white", color="black"),
        panel.grid = element_blank(), 
        axis.text=element_text(color="black",size=16),
        axis.ticks=element_blank(),
        axis.title.y = element_text(color="black", size=16),
      axis.title.x= element_text(color="black", size=16),
        strip.background = element_rect(color="black", fill="white"),
        strip.text =element_text(color="black", size=12),
                               legend.text=element_text(size=12),
     strip.text.y=element_text(angle=0),
     strip.text.x=element_text(angle=0),
   plot.title = element_text(hjust = 0.5, size=12),
   legend.position = "none",
   legend.background = element_rect(fill='white'),
   legend.key = element_rect(fill='white'),
        legend.title=element_blank() ) +
  ylab("Normalized fluorescence")



```


```{r all together for fig 2}

flim_legend <- arrangeGrob(flim_pure, 
                          flim_pure_gradient_legend,
                           ncol=2, widths=c(3,1))


spec_legend <- arrangeGrob(spectra_plot, 
                          flim_pure_shape_legend,
                           ncol=2, widths=c(3,1))


tablea<-textGrob(c("A"), gp=gpar(fontsize=40), vjust=c(-1,0), hjust=c(.5,0))
tableb<-textGrob(c("B"), gp=gpar(fontsize=40), vjust=c(-1,0), hjust=c(.5,0))

top_panel <- arrangeGrob(tablea, spec_legend, ncol=2, widths=c(1,12))
bottom_panel <- arrangeGrob(tableb, flim_legend, ncol=2, widths=c(1,12))

figure2 <- arrangeGrob(top_panel, bottom_panel, nrow=2)

ggsave(plot=figure2,filename ="/Users/sltg/Documents/GitHub/PseudomonasFLIM/Output/Paper/Figures/fig2_spectra_phasor.eps", device ='eps', height=7, width=7.5 )

```
